#!/usr/bin/env python3
"""
HexLang - A programming language for humans
Main compiler and interpreter entry point
"""

import sys
import os
import argparse
import py_compile

# Import the core interpreter from hex.py
from hex import run_hex

def compile_to_python(hexlang_file, output_file=None):
    """Compile HexLang to Python bytecode"""
    if output_file is None:
        output_file = hexlang_file.replace('.hexlang', '.pyc')
    
    with open(hexlang_file, 'r') as f:
        hex_code = f.read()
    
    # Generate Python wrapper code
    python_code = f'''#!/usr/bin/env python3
# Auto-generated from {hexlang_file}
import sys
sys.path.insert(0, {repr(os.path.dirname(os.path.abspath(__file__)))})
from hex import run_hex

hex_code = {repr(hex_code)}
run_hex(hex_code)
'''
    
    # Write intermediate Python file
    py_file = hexlang_file.replace('.hexlang', '_compiled.py')
    with open(py_file, 'w') as f:
        f.write(python_code)
    
    print(f"✓ Compiled {hexlang_file} to {py_file}")
    
    # Compile to bytecode
    try:
        py_compile.compile(py_file, cfile=output_file, doraise=True)
        print(f"✓ Generated bytecode: {output_file}")
    except py_compile.PyCompileError as e:
        print(f"✗ Compilation error: {e}")
        sys.exit(1)
    
    return py_file, output_file

def main():
    """Main entry point for hexlang compiler/interpreter"""
    parser = argparse.ArgumentParser(
        description='HexLang - A programming language for humans',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  hexlang run program.hexlang          # Run a HexLang program
  hexlang compile program.hexlang      # Compile to Python bytecode
  hexlang demo                          # Run the demo program
  
For more information, visit: https://github.com/HexCodeLang/hexlang
        '''
    )
    
    parser.add_argument('command', 
                       choices=['run', 'compile', 'demo'],
                       help='Command to execute')
    parser.add_argument('file', 
                       nargs='?',
                       help='HexLang source file (.hexlang)')
    parser.add_argument('-o', '--output',
                       help='Output file for compilation')
    parser.add_argument('--version',
                       action='version',
                       version='HexLang 1.0.0')
    
    args = parser.parse_args()
    
    if args.command == 'demo':
        # Run the demo program
        demo_file = os.path.join(os.path.dirname(__file__), 'examples', 'demo.hexlang')
        if not os.path.exists(demo_file):
            print(f"✗ Demo file not found: {demo_file}")
            sys.exit(1)
        
        print("=" * 50)
        print("🍭 HexLang Demo")
        print("=" * 50)
        with open(demo_file, 'r') as f:
            hex_code = f.read()
        run_hex(hex_code)
        
    elif args.command == 'run':
        if not args.file:
            print("✗ Error: file argument required for 'run' command")
            parser.print_help()
            sys.exit(1)
        
        if not os.path.exists(args.file):
            print(f"✗ Error: File not found: {args.file}")
            sys.exit(1)
        
        with open(args.file, 'r') as f:
            hex_code = f.read()
        run_hex(hex_code)
        
    elif args.command == 'compile':
        if not args.file:
            print("✗ Error: file argument required for 'compile' command")
            parser.print_help()
            sys.exit(1)
        
        if not os.path.exists(args.file):
            print(f"✗ Error: File not found: {args.file}")
            sys.exit(1)
        
        compile_to_python(args.file, args.output)

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("HexLang - A programming language for humans")
        print("Usage: hexlang <command> [options]")
        print("\nCommands:")
        print("  run <file>      Run a HexLang program")
        print("  compile <file>  Compile to Python bytecode")
        print("  demo            Run the demo program")
        print("\nFor more help: hexlang --help")
        sys.exit(0)
    
    main()
